// Curriculum data for BBLFKM - Kiberbiztonsági mérnöki
// Extracted from curriculum image, with current semester BLF codes as authoritative

import { CurriculumSemester, CurriculumDependency } from "../types";

export type VisualCategory = "programming" | "cybersecurity" | "networks" | "math" | "project" | "elective" | "pe" | "thesis";

export const subjectVisualCategories: Record<string, VisualCategory> = {
  "inf-1": "programming",
  "bbxin2kblf": "programming",
  "bbxpr12blf": "programming",
  "matek-2": "math",
  "btxmak2blf": "math",
  "hirkoz": "networks",
  "bbxvn12blf": "networks",
  "ik-halo": "networks",
  "halo-felh": "networks",
  "ik-mobil": "networks",
  "tavkozlo": "networks",
  "bbxvd12blf": "cybersecurity",
  "bbxdv12blf": "cybersecurity",
  "kiber-alap": "cybersecurity",
  "elek-info": "cybersecurity",
  "kockazat": "cybersecurity",
  "kiber-epit": "cybersecurity",
  "kiber-meres": "cybersecurity",
  "web-wifi": "cybersecurity",
  "virus": "cybersecurity",
  "etikus-1": "cybersecurity",
  "etikus-2": "cybersecurity",
  "ibir": "cybersecurity",
  "kozszfer": "cybersecurity",
  "audit": "cybersecurity",
  "okmany": "cybersecurity",
  "vagyon": "cybersecurity",
  "projekt-1": "project",
  "projekt-2": "project",
  "kiber-proj-1": "project",
  "kiber-proj-2": "project",
  "projekt-mgmt": "project",
  "info-proj": "project",
  "szabad-1": "elective",
  "szabad-2": "elective",
  "szabad-3": "elective",
  "testneveles-1": "pe",
  "ottesi2blf": "pe",
  "testneveles-3": "pe",
  "testneveles-4": "pe",
  "szakdolgozat": "thesis",
  "gazdasag": "project",
  "fizika": "math",
  "info-jog": "cybersecurity",
  "tanulastech": "elective",
  "elektro": "math",
  "patronalas": "elective",
  "uzemelt": "cybersecurity",
  "os-db": "cybersecurity",
  "arch-alap": "math",
};

export const visualCategoryColors: Record<VisualCategory, { bg: string; text: string; border: string; accent: string }> = {
  programming: { bg: "bg-blue-50", text: "text-blue-700", border: "border-blue-200", accent: "#3b82f6" },
  cybersecurity: { bg: "bg-rose-50", text: "text-rose-700", border: "border-rose-200", accent: "#e11d48" },
  networks: { bg: "bg-cyan-50", text: "text-cyan-700", border: "border-cyan-200", accent: "#0891b2" },
  math: { bg: "bg-violet-50", text: "text-violet-700", border: "border-violet-200", accent: "#8b5cf6" },
  project: { bg: "bg-amber-50", text: "text-amber-700", border: "border-amber-200", accent: "#f59e0b" },
  elective: { bg: "bg-purple-50", text: "text-purple-700", border: "border-purple-200", accent: "#a855f7" },
  pe: { bg: "bg-emerald-50", text: "text-emerald-700", border: "border-emerald-200", accent: "#10b981" },
  thesis: { bg: "bg-slate-50", text: "text-slate-700", border: "border-slate-200", accent: "#64748b" },
};

export const curriculumSemesters: CurriculumSemester[] = [
  {
    semesterNumber: 1,
    name: "1. félév",
    subjects: [
      { id: "inf-1", name: "Informatika I.", code: null, isRequired: true, isCompleted: false },
      { id: "hirkoz", name: "Hírközléstechnika", code: null, isRequired: true, isCompleted: false },
      { id: "gazdasag", name: "Gazdasági és vállalkozási ismeretek / Startup ismeretek", code: null, isRequired: true, isCompleted: false },
      { id: "fizika", name: "Mérnöki fizika", code: null, isRequired: true, isCompleted: false },
      { id: "info-jog", name: "Információbiztonság jogi- és humán aspektusai", code: null, isRequired: true, isCompleted: false },
      { id: "tanulastech", name: "Tanulástechnika és tutorálás", code: null, isRequired: true, isCompleted: false },
      { id: "elektro", name: "Elektrotechnika, digitális technika", code: null, isRequired: true, isCompleted: false },
      { id: "testneveles-1", name: "Testnevelés I.", code: null, isRequired: true, isCompleted: false },
      { id: "patronalas", name: "Patronálás", code: null, isRequired: true, isCompleted: false },
      { id: "projekt-1", name: "Projektfeladat", code: null, isRequired: true, isCompleted: false },
    ],
  },
  {
    semesterNumber: 2,
    name: "2. félév",
    isCurrent: true,
    subjects: [
      { id: "btxmak2blf", name: "Matematika I.", code: "BTXMAK2BLF", isRequired: true, isCompleted: false },
      { id: "bbxin2kblf", name: "Informatika II. (laborgyak)", code: "BBXIN2KBLF", isRequired: true, isCompleted: false },
      { id: "bbxpr12blf", name: "Programozás", code: "BBXPR12BLF", isRequired: true, isCompleted: false },
      { id: "bbxvd12blf", name: "Adatvédelem, adatbiztonság", code: "BBXVD12BLF", isRequired: true, isCompleted: false },
      { id: "bbxdv12blf", name: "Dokumentumvédelem és adminisztratív biztonság", code: "BBXDV12BLF", isRequired: true, isCompleted: false },
      { id: "bbxvn12blf", name: "Vezetékes és vezeték nélküli hálózatok", code: "BBXVN12BLF", isRequired: true, isCompleted: false },
      { id: "ottesi2blf", name: "Testnevelés II.", code: "OTTESI2BLF", isRequired: true, isCompleted: false },
    ],
  },
  {
    semesterNumber: 3,
    name: "3. félév",
    subjects: [
      { id: "matek-2", name: "Matematika II.", code: null, isRequired: true, isCompleted: false },
      { id: "kiber-alap", name: "Kiberbiztonság alapjai, szabványai", code: null, isRequired: true, isCompleted: false },
      { id: "elek-info", name: "Elektronikus információbiztonsági ismeretek", code: null, isRequired: true, isCompleted: false },
      { id: "kockazat", name: "Információbiztonsági kockázatok kezelése", code: null, isRequired: true, isCompleted: false },
      { id: "projekt-2", name: "Projektfeladat II.", code: null, isRequired: true, isCompleted: false },
      { id: "kiber-epit", name: "Kiberbiztonság kiépítése", code: null, isRequired: true, isCompleted: false },
      { id: "ik-mobil", name: "Infokommunikációs rendszerek, mobil kommunikáció", code: null, isRequired: true, isCompleted: false },
      { id: "testneveles-3", name: "Testnevelés III.", code: null, isRequired: true, isCompleted: false },
    ],
  },
  {
    semesterNumber: 4,
    name: "4. félév",
    subjects: [
      { id: "projekt-mgmt", name: "Projektmunka és menedzsment alapjai", code: null, isRequired: true, isCompleted: false },
      { id: "ik-halo", name: "Infokommunikációs technológiák, hálózatbiztonság", code: null, isRequired: true, isCompleted: false },
      { id: "os-db", name: "Operációs rendszerek és adatbázis tervezés", code: null, isRequired: true, isCompleted: false },
      { id: "arch-alap", name: "Számítógépes architektúrák alapjai", code: null, isRequired: true, isCompleted: false },
      { id: "szabad-1", name: "Szabadon választható I.", code: null, isRequired: false, isCompleted: false },
      { id: "kiber-meres", name: "Kiberbiztonsági mérések", code: null, isRequired: true, isCompleted: false },
      { id: "tavkozlo", name: "Távközlési informatika", code: null, isRequired: true, isCompleted: false },
      { id: "testneveles-4", name: "Testnevelés IV.", code: null, isRequired: true, isCompleted: false },
    ],
  },
  {
    semesterNumber: 5,
    name: "5. félév",
    subjects: [
      { id: "ibir", name: "Információbiztonsági irányítási rendszerek / IBIR", code: null, isRequired: true, isCompleted: false },
      { id: "uzemelt", name: "Informatikai rendszerek üzemeltetése", code: null, isRequired: true, isCompleted: false },
      { id: "info-proj", name: "Információbiztonsági projektmenedzsment", code: null, isRequired: true, isCompleted: false },
      { id: "vagyon", name: "Vagyonvédelmi rendszerek", code: null, isRequired: true, isCompleted: false },
      { id: "web-wifi", name: "Web, WiFi biztonság, sérülékenységvizsgálat, töréstesztek", code: null, isRequired: true, isCompleted: false },
      { id: "szabad-2", name: "Szabadon választható II.", code: null, isRequired: false, isCompleted: false },
    ],
  },
  {
    semesterNumber: 6,
    name: "6. félév",
    subjects: [
      { id: "okmany", name: "Kiberbiztonság okmányrendszere", code: null, isRequired: true, isCompleted: false },
      { id: "halo-felh", name: "Számítógéphálózati és felhőbiztonság", code: null, isRequired: true, isCompleted: false },
      { id: "etikus-1", name: "Kiberbiztonság / etikus hacking I.", code: null, isRequired: true, isCompleted: false },
      { id: "kiber-proj-1", name: "Kiberbiztonsági projektfeladat I.", code: null, isRequired: true, isCompleted: false },
      { id: "audit", name: "Információbiztonsági auditor felkészítés és auditálás", code: null, isRequired: true, isCompleted: false },
      { id: "szabad-3", name: "Szabadon választható III.", code: null, isRequired: false, isCompleted: false },
      { id: "virus", name: "Vírustámadási és adathalász technikák", code: null, isRequired: true, isCompleted: false },
    ],
  },
  {
    semesterNumber: 7,
    name: "7. félév",
    subjects: [
      { id: "szakdolgozat", name: "Szakdolgozat", code: null, isRequired: true, isCompleted: false },
      { id: "etikus-2", name: "Kiberbiztonság / etikus hacking II.", code: null, isRequired: true, isCompleted: false },
      { id: "kozszfer", name: "Információbiztonság követelményei a közszférában", code: null, isRequired: true, isCompleted: false },
      { id: "kiber-proj-2", name: "Kiberbiztonsági projektfeladat II.", code: null, isRequired: true, isCompleted: false },
    ],
  },
];

export const curriculumDependencies: CurriculumDependency[] = [
  { from: "inf-1", to: "bbxin2kblf", confidence: "estimated" },
  { from: "bbxin2kblf", to: "uzemelt", confidence: "estimated" },
  { from: "btxmak2blf", to: "matek-2", confidence: "estimated" },
  { from: "testneveles-1", to: "ottesi2blf", confidence: "estimated" },
  { from: "ottesi2blf", to: "testneveles-3", confidence: "estimated" },
  { from: "testneveles-3", to: "testneveles-4", confidence: "estimated" },
  { from: "projekt-1", to: "projekt-2", confidence: "estimated" },
  { from: "projekt-2", to: "kiber-proj-1", confidence: "estimated" },
  { from: "kiber-proj-1", to: "kiber-proj-2", confidence: "estimated" },
  { from: "etikus-1", to: "etikus-2", confidence: "estimated" },
  { from: "bbxvn12blf", to: "ik-halo", confidence: "estimated" },
  { from: "ik-halo", to: "halo-felh", confidence: "estimated" },
  { from: "bbxvd12blf", to: "ibir", confidence: "estimated" },
  { from: "bbxdv12blf", to: "kockazat", confidence: "estimated" },
  { from: "kiber-alap", to: "kiber-meres", confidence: "estimated" },
  { from: "kiber-meres", to: "web-wifi", confidence: "estimated" },
  { from: "web-wifi", to: "etikus-1", confidence: "estimated" },
];

// Keep old exports for backward compatibility
export const curriculumNodes: any[] = [];
export const curriculumEdges: any[] = [];
