// Real deadline and exam data for current semester
// Priority: Exam Sprint mode for Programozás and Informatika II. (exam on 2026-05-09)

import { Deadline } from "../types";

export const deadlines: Deadline[] = [
  {
    id: "dokumentumvedelem-beadando-1",
    subjectName: "Dokumentumvédelem és adminisztratív biztonság",
    type: "assignment",
    firstDeadline: "2026-03-20",
    secondDeadline: "2026-04-14",
    isDone: true,
    noMoreActionNeeded: false,
    gradeReceived: false,
  },
  {
    id: "adatvedelem-beadando-1",
    subjectName: "Adatvédelem, adatbiztonság",
    type: "assignment",
    firstDeadline: "2026-04-14",
    secondDeadline: null,
    isDone: true,
    noMoreActionNeeded: false,
    gradeReceived: false,
  },
  {
    id: "tanulasmodszertan-online-1",
    subjectName: "Tanulásmódszertan",
    type: "online",
    firstDeadline: "2026-05-04",
    secondDeadline: null,
    isDone: true,
    noMoreActionNeeded: true,
    gradeReceived: false,
  },
  {
    id: "programozas-vizsga-1",
    subjectName: "Programozás",
    type: "exam",
    firstDeadline: "2026-05-09",
    secondDeadline: null,
    isDone: false,
    noMoreActionNeeded: false,
    gradeReceived: false,
    priority: "urgent",
  },
  {
    id: "informatika-ii-vizsga-1",
    subjectName: "Informatika II. (laborgyak)",
    type: "exam",
    firstDeadline: "2026-05-09",
    secondDeadline: null,
    isDone: false,
    noMoreActionNeeded: false,
    gradeReceived: false,
    priority: "urgent",
  },
  {
    id: "testneveles-ii-alkalom-1",
    subjectName: "Testnevelés II.",
    type: "single_occasion",
    firstDeadline: "2026-05-23",
    secondDeadline: null,
    isDone: false,
    noMoreActionNeeded: false,
    gradeReceived: false,
  },
  {
    id: "matematika-i-vizsga-1",
    subjectName: "Matematika I.",
    type: "exam",
    firstDeadline: "2026-05-23",
    secondDeadline: null,
    isDone: false,
    noMoreActionNeeded: false,
    gradeReceived: false,
  },
  {
    id: "halozatok-vizsga-1",
    subjectName: "Vezetékes és vezetéknélküli hálózatok",
    type: "exam",
    firstDeadline: "2026-05-23",
    secondDeadline: null,
    isDone: false,
    noMoreActionNeeded: false,
    gradeReceived: false,
  },
];
