import { Subject } from "../types";

export const subjects: Subject[] = [
  {
    id: "bbxpr12blf",
    code: "BBXPR12BLF",
    name: "Programozás",
    shortName: "Programozás",
    semesterId: "2025-26-2",
    category: "Kötelező törzsanyag",
    credits: 5,
    recommendedSemester: 2,
    requirementType: "Vizsga",
    mode: "exam_unknown",
    completionStatus: "not_completed",
    gradeType: "grade",
    color: "#3b82f6",
    followUpSubjectCount: 0,
    prerequisiteSubjectIds: [],
    unlocksSubjectIds: [],
  },
  {
    id: "btxtn12blf",
    code: "BTXTN12BLF",
    name: "Tanulásmódszertan",
    shortName: "Tanulás",
    semesterId: "2025-26-2",
    category: "Kötelező törzsanyag",
    credits: 1,
    recommendedSemester: 2,
    requirementType: "Full online",
    mode: "full_online",
    completionStatus: "completed",
    gradeType: "pass_fail",
    color: "#10b981",
    followUpSubjectCount: 0,
    prerequisiteSubjectIds: [],
    unlocksSubjectIds: [],
  },
  {
    id: "bbxvd12blf",
    code: "BBXVD12BLF",
    name: "Adatvédelem, adatbiztonság",
    shortName: "Adatvédelem",
    semesterId: "2025-26-2",
    category: "Kötelező törzsanyag",
    credits: 5,
    recommendedSemester: 2,
    requirementType: "Beadandó",
    mode: "assignment",
    completionStatus: "in_progress",
    gradeType: "grade",
    color: "#8b5cf6",
    followUpSubjectCount: 0,
    prerequisiteSubjectIds: [],
    unlocksSubjectIds: [],
  },
  {
    id: "bbxvn12blf",
    code: "BBXVN12BLF",
    name: "Vezetékes és vezetéknélküli hálózatok",
    shortName: "Hálózatok",
    semesterId: "2025-26-2",
    category: "Kötelező törzsanyag",
    credits: 4,
    recommendedSemester: 2,
    requirementType: "Vizsga",
    mode: "exam_unknown",
    completionStatus: "not_completed",
    gradeType: "grade",
    color: "#06b6d4",
    followUpSubjectCount: 0,
    prerequisiteSubjectIds: [],
    unlocksSubjectIds: [],
  },
  {
    id: "bbxin2kblf",
    code: "BBXIN2KBLF",
    name: "Informatika II. (laborgyak)",
    shortName: "Informatika II.",
    semesterId: "2025-26-2",
    category: "Kötelező törzsanyag",
    credits: 5,
    recommendedSemester: 2,
    requirementType: "Vizsga",
    mode: "exam_unknown",
    completionStatus: "not_completed",
    gradeType: "grade",
    color: "#f59e0b",
    followUpSubjectCount: 0,
    prerequisiteSubjectIds: [],
    unlocksSubjectIds: [],
  },
  {
    id: "bbxdv12blf",
    code: "BBXDV12BLF",
    name: "Dokumentumvédelem és adminisztratív biztonság",
    shortName: "Dokumentumvédelem",
    semesterId: "2025-26-2",
    category: "Kötelező törzsanyag",
    credits: 4,
    recommendedSemester: 2,
    requirementType: "Beadandó",
    mode: "assignment",
    completionStatus: "in_progress",
    gradeType: "grade",
    color: "#f43f5e",
    followUpSubjectCount: 0,
    prerequisiteSubjectIds: [],
    unlocksSubjectIds: [],
  },
  {
    id: "btxmak2blf",
    code: "BTXMAK2BLF",
    name: "Matematika I.",
    shortName: "Matek I.",
    semesterId: "2025-26-2",
    category: "Kötelező törzsanyag",
    credits: 6,
    recommendedSemester: 2,
    requirementType: "Vizsga",
    mode: "exam_unknown",
    completionStatus: "not_completed",
    gradeType: "grade",
    color: "#6366f1",
    followUpSubjectCount: 0,
    prerequisiteSubjectIds: [],
    unlocksSubjectIds: [],
  },
  {
    id: "ottesi2blf",
    code: "OTTESI2BLF",
    name: "Testnevelés II.",
    shortName: "Tesó II.",
    semesterId: "2025-26-2",
    category: "Kötelező törzsanyag",
    credits: 1,
    recommendedSemester: 2,
    requirementType: "Megfelelt / Nem megfelelt",
    mode: "single_occasion_pass_fail",
    completionStatus: "not_completed",
    gradeType: "pass_fail",
    color: "#64748b",
    followUpSubjectCount: 0,
    prerequisiteSubjectIds: [],
    unlocksSubjectIds: [],
  },
];
